version: 2
jobs:
  lint-scripts:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: lint
          command: |
            shellcheck -x .scripts/repo-sync.sh
            shellcheck -x .scripts/gen_packages.sh
            shellcheck -x .scripts/index_repo.sh
            shellcheck -x test/e2e-kind.sh
  lint-charts:
    docker:
      - image: gcr.io/kubernetes-charts-ci/test-image:v3.0.1
    steps:
      - checkout
      - run:
          name: lint
          command: |
            git remote add k8s https://github.com/rimusz/charts
            git fetch k8s master
            ct lint --config test/ct.yaml
  install-charts:
    machine: true
    environment:
      CHART_TESTING_IMAGE: quay.io/helmpack/chart-testing
      CHART_TESTING_TAG: v2.0.1
      TEST_IMAGE: gcr.io/kubernetes-charts-ci/test-image
      TEST_IMAGE_TAG: v3.0.1
      CHARTS_REPO: https://github.com/rimusz/charts
      K8S_VERSION: v1.11.3
    steps:
      - checkout
      - run:
          name: install.
          command: |
            test/e2e-kind.sh
          no_output_timeout: 3600
workflows:
  version: 2
  lint_and_install:
    jobs:
      - lint-scripts
      - lint-charts:
          requires:
            - lint-scripts
      - install-charts:
          requires:
            - lint-charts
